BASIC_DIMENSION = 20
SCOREBOARD_POSITION = (0, 270)
SCOREBOARD_ALIGMENT = "center"
SCOREBOARD_FONT = ("Courier", 16, "normal")
MAP_BOUNDARIES = (-14 * BASIC_DIMENSION, 14 * BASIC_DIMENSION, -14 * BASIC_DIMENSION, 14 * BASIC_DIMENSION)
